name: Deploy Training Bot to VPS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # -----------------
      # FRONTEND
      # -----------------

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build frontend
        run: npm ci && npm run build
        working-directory: ui

      # -----------------
      # BACKEND
      # -----------------

      - name: Set up Go 1.24
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Build Go binary
        run: |
          CGO_ENABLED=0 go build -o training-tg-bot ./cmd/main.go
          sha256sum training-tg-bot

      - name: Check binary exists
        run: |
          ls -lh training-tg-bot
          file training-tg-bot

      # -----------------
      # DEPLOY TO VPS
      # -----------------

      - name: Copy binary to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "training-tg-bot"
          target: "/opt/training-tg-bot/"

      - name: Deploy systemd service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            sudo systemctl stop training-tg-bot

            cd /opt/training-tg-bot
            echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" > .env
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
            echo "VAPID_PRIVATE_KEY=${{ secrets.VAPID_PRIVATE_KEY }}" >> .env
            echo "VAPID_PUBLIC_KEY=${{ secrets.VAPID_PUBLIC_KEY }}" >> .env
            echo "TELEGRAM_BOT_ID=${{ secrets.TELEGRAM_BOT_ID }}" >> .env

            sudo systemctl start training-tg-bot
            sudo systemctl status training-tg-bot --no-pager
