name: Deploy Training Bot to VPS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go 1.24
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Build Go binary
        run: |
          CGO_ENABLED=0 go build -o training-tg-bot ./cmd/main.go

      - name: Copy binary to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "training-tg-bot"
          target: "/opt/training-tg-bot/"


      - name: Start app
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /opt/training-tg-bot
            ls -al
            export TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
            export DATABASE_URL=${{ secrets.DATABASE_URL }}
            echo TELEGRAM_TOKEN
            echo DATABASE_URL
            ./training-tg-bot
